// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace RegistroNotas.Datos
{
    using System.ComponentModel.DataAnnotations;
    public partial class Alumno
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(240)]
        public string Nombres { get; set; }
        [Required]
        [StringLength(120)]
        public string PrimerApellido { get; set; }
        [StringLength(120)]
        public string SegundoApellido { get; set; }
        [Required]
        [StringLength(50)]
        public string DocumentoIdentificacion { get; set; }
        [Required]
        [StringLength(256)]
        public string Email { get; set; }
    }
}