// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace RegistroNotas.Datos
{
    using System.ComponentModel.DataAnnotations;
    public partial class Materia
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(25)]
        public string Codigo { get; set; }
        [Required]
        [StringLength(240)]
        public string Nombre { get; set; }
    }
}