// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace RegistroNotas.Datos
{
    using Microsoft.EntityFrameworkCore;
    public partial class RegistronotasContext : DbContext
    {
        public RegistronotasContext()
        {
        }
        public RegistronotasContext(DbContextOptions<RegistronotasContext> options)
            : base(options)
        {
        }
        public virtual DbSet<Alumno> Alumno { get; set; }
        public virtual DbSet<Materia> Materia { get; set; }
        public virtual DbSet<Nota> Nota { get; set; }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Modern_Spanish_CI_AS");

            OnModelCreatingPartial(modelBuilder);
        }
        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}