// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace RegistroNotas.Datos
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class Nota
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public int IdAlumno { get; set; }
        [Required]
        public int IdMateria { get; set; }
        [Required]
        [Column("Calificacion", TypeName = "decimal(2, 1)")]
        public decimal Calificacion { get; set; }
    }
}