// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace RegistroNotas.Datos
{
    public partial class NotaPromedio
    {
        public string Estudiante { get; set; }
        public string Materia { get; set; }
        public decimal Calificacion { get; set; }
    }
}